### PR TITLE
Add PSR-17 and PSR-18 support

### LINKED ISSUE #13: Add PSR-17 and PSR-18 support
The problem is that my projects use different Guzzle versions (5 and 6) and share some packages, so I'm unable to install this agent due to Guzzle 5 usage.

PR - #4 #14

### PR DESCRIPTION
**Pull request by CSharpRU**
Also I formatted all code according to PHPStorm Code Style settings.

Reason behind this is that my projects use different Guzzle versions (5 and 6) and share some packages, so I'm unable to install this agent due to Guzzle 5 usage.

Resolves #13

### CODE REVIEW

**Comment by dstepe** [comment]
This sounds good, but I'll need some time to look into the implications of implementing those PSRs. I've not had a reason to dig into them yet. It would be much easier to evaluate this PR if it only included the functional changes. Can you resubmit this with only the functional changes? I'm all for establishing a code format standard, but not concurrent with other changes.

Regarding code style, I'm not sure that "PHPStorm Code Style settings" is an actual code style. PhpStorm applies the settings you choose. Individual users may change those settings between installations. I'm more inclined to go with PSR-1/PSR-2 or PSR-12 and use code style check in the build to enforce it. PhpStorm can be told to set your style from one of those.

**Comment by dstepe** [comment]
If you are still interested in adding PSR-17 and PSR-18 support, please review the new `.github/CONTRIBUTING.md` guide. I just merged a PR to apply a code style, so please follow that. You will need to open an issue for the PSR-17/18 support and will likely want to start a new branch from the updated master.

**Comment by CSharpRU** [comment]
I have merged new master and ran new code style fix command.

**Comment by CSharpRU** [comment]
Resolves #13

**Comment by CSharpRU** [comment]
See #14 for functional changes only

**Comment by dstepe** [comment]
Superseded by #14

**Pull request closed without merging**
