### PR TITLE
Resolve issue where APM requires an int

### PR DESCRIPTION
**Pull request by cmtickle**
Resolves the issue where the current 8.0.1 version Timestamp class creates a float with scientific notation when serialised. 

The APM server requires an integer and therefor fails to ingest results created with this package.

(Tested with PHP 8.1)

### CODE REVIEW

**Comment by dstepe** [comment]
Thanks for the submission, @cmtickle . The timestamp value was previously a problem for someone running PHP on a Windows machine. He believed PHP was running 32-bit and therefore the int max was lower. See #44 for details. That's what caused us to try keeping the timestamp as a float internally.

I don't know why a 32-bit version was being used, but knowing someone was relying on it, I would prefer not to make this change without considering that impact. While it may be time to leave 32-bit support behind, that should be reflected in the README and at least a minor version release.

We should also update the PHP requirement in `composer.json` to specify 64-bit:

```
"php-64bit" : ">= 7.1",
```
as documented by composer: https://getcomposer.org/doc/01-basic-usage.md#platform-packages

Can you add that change?

**Comment by cmtickle** [comment]
@dstepe thanks for the code review and suggestion. I've made the change to composer.json and tested the branch from my repo in docker 64 bit.
 
It works as expected.

I tried various ways to maintain compatibility/not create a true integer before I submitted this PR but hadn't been successful.

**Comment by dstepe** [comment]
I'd like to update the `README` and make another couple of changes before releasing. I created a new `8.1-dev` branch if you can change this PR to merge to it.

**Comment by cmtickle** [comment]
Changed to merge into 8.1-dev. Thanks @dstepe

**Review by dstepe — APPROVED** [review]

**Pull request merged**
